# Generated by Django 3.2.16 on 2023-01-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holding',
        ),
    ]
