# Generated by Django 3.2.16 on 2023-01-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_whisky_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whisky_name',
            old_name='name',
            new_name='item_name',
        ),
    ]
