# Generated by Django 3.2.16 on 2023-01-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_name_whisky_name_item_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whisky_name',
            new_name='Whisky',
        ),
    ]
