# Generated by Django 3.2.16 on 2023-01-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_whisky_name_whisky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisky',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
