# Generated by Django 3.2.16 on 2023-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_whiskybooze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whisky2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=300)),
            ],
        ),
    ]
