# Generated by Django 3.2.16 on 2023-01-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_whisky2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisky2',
            name='item_name',
            field=models.CharField(max_length=300),
        ),
    ]
