# Generated by Django 3.2.16 on 2023-01-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_whiskybooze2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiskybooze2',
            name='item_name',
            field=models.CharField(max_length=500),
        ),
    ]
