# Generated by Django 3.2.16 on 2023-01-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20230121_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiskybooze2',
            name='item_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='whiskybooze2',
            name='price',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='whiskybooze2',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
